[workspace]
members = [
  "packages/dchain-test-tube",
  "packages/test-tube",
  "test_contracts/*",
]
resolver = "2"

[workspace.dependencies]
#dchain-sdk-proto = { path = "../protocol-proto-rs/cosmos-sdk-proto" }
dchain-sdk-proto = { git = "https://github.com/d-foundation/dchain-sdk-proto.git", tag = "v0.11.0" }
cosmrs = {version = "0.22.0", features = ["cosmwasm"]}
cosmwasm-std = "3.0.2"
